services:
  app:
    build: .
    container_name: mushroom-classifier
    ports:
      - "8000:8000" # FastAPI
      - "5000:5000" # MLflow UI
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=/app/mlruns
    networks:
      - mlops-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  # Optional: Add a database service for MLflow tracking
  # db:
  #   image: postgres:13
  #   container_name: mlflow-db
  #   environment:
  #     - POSTGRES_USER=mlflow
  #     - POSTGRES_PASSWORD=mlflow
  #     - POSTGRES_DB=mlflow
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - mlops-network

  # Optional: Add MinIO for artifact storage
  # minio:
  #   image: minio/minio
  #   container_name: mlflow-minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     - MINIO_ROOT_USER=minio
  #     - MINIO_ROOT_PASSWORD=minio123
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio-data:/data
  #   networks:
  #     - mlops-network

networks:
  mlops-network:
    driver: bridge

# volumes:
#   postgres-data:
#   minio-data: 
